// scenes/protopirate_scene_protocol_help.c
// In-app documentation: protocoles par marque et modele de voiture
#include "../protopirate_app_i.h"
#include <notification/notification_messages.h>

#define TAG "ProtoPirateProtoHelp"

static const char* help_text =
    "=== QUICK START ===\n"
    "\n"
    "1. RECEIVE: pick freq,\n"
    "   point at keyfob, press OK\n"
    "2. SAVED CAPTURES: view\n"
    "   decoded signals, CSV,\n"
    "   emulate, delete\n"
    "3. SUB DECODE: load .sub\n"
    "   files from SD card\n"
    "4. CONFIG: freq, hopping,\n"
    "   TX power, auto-save\n"
    "5. TIMING TUNER: compare\n"
    "   fob timing vs constants\n"
    "\n"
    "=== FORD ===\n"
    "\n"
    "V0 [AM650 315/433]\n"
    "Manchester, Rolling Code,\n"
    "CRC GF(2). Decode+Encode\n"
    "Models:\n"
    "Fiesta 08-12, Focus 04-11,\n"
    "Mondeo 06-10, Kuga 08-12,\n"
    "Transit 06-14, C-Max 03-10,\n"
    "Galaxy/Fusion/S-Max 06-10,\n"
    "Explorer 10-15, Mustang 08-16\n"
    "\n"
    "V1 [F4 315/433]\n"
    "Manchester, Rolling Code,\n"
    "CRC16. Decode+Encode\n"
    "Models:\n"
    "Focus III (11-18), Kuga II /\n"
    "Escape (12-19), Mondeo 10-14,\n"
    "C/Grand C-Max 10-19,\n"
    "Galaxy/S-Max 10-15,\n"
    "Ranger 11-15, Transit 14-18\n"
    "\n"
    "V2 [F4 434]\n"
    "Manchester, Replay only.\n"
    "Decode+Encode\n"
    "\n"
    "V3 [AM650+F4 434]\n"
    "Manchester, Rolling Code.\n"
    "Decode only (no encode)\n"
    "\n"
    "=== VAG ===\n"
    "(VW/Audi/Seat/Skoda)\n"
    "\n"
    "AUT64+XTEA [AM650 434.42]\n"
    "Manchester. Decode+Encode\n"
    "Models:\n"
    "Golf 4/5/6, Passat B5/B6/B7,\n"
    "Polo, Jetta, Touran, Tiguan,\n"
    "Caddy, Beetle 11-19,\n"
    "Scirocco 08-17, Eos 10-15\n"
    "Audi: A1/A2/A3/A4/A6/A8,\n"
    "S3/S4/RS4/S6/RS6, TT, R8,\n"
    "Q3 11-18 (tous avant 2015)\n"
    "Seat: Leon, Ibiza, Altea,\n"
    "Toledo, Exeo, Mii\n"
    "Skoda: Octavia, Fabia,\n"
    "Superb, Yeti, Rapid, Roomster\n"
    "\n"
    "=== PSA ===\n"
    "(Peugeot/Citroen)\n"
    "\n"
    "XTEA+XOR+CRC8 [AM650+F3]\n"
    "Manchester, 315/433 MHz\n"
    "Decode+Encode (BF plugin)\n"
    "Mode 1 (older V0):\n"
    "Peugeot: 207 09-15, 307\n"
    "05-08, 407 04-11, C5 09-17\n"
    "Citroen: C3 02-13, C5 09-17\n"
    "Mode 2 (newer F3):\n"
    "Peugeot: 208/2008/3008/\n"
    "308/408/508/301/RCZ\n"
    "Partner 09-16, 5008 09-16\n"
    "Citroen: C3 14-16, C4/C4L\n"
    "10-18, C4 Picasso/Cactus,\n"
    "C-Elysee, DS3/DS4/DS5,\n"
    "Jumpy 09-16+\n"
    "\n"
    "=== KIA / HYUNDAI ===\n"
    "\n"
    "V0 [FM476 315/433]\n"
    "PWM, Rolling Code, CRC8\n"
    "\n"
    "V1 [AM650 315/433]\n"
    "Manchester, Rolling Code,\n"
    "CRC4\n"
    "\n"
    "V2 [FM476 315/433]\n"
    "Manchester, Rolling Code,\n"
    "CRC4\n"
    "\n"
    "V3/V4 [FM476 315/433]\n"
    "PWM, KeeLoq, CRC4\n"
    "Models:\n"
    "Sportage 08-16, Sorento II\n"
    "09-20, Mohave 08-16\n"
    "\n"
    "V5 [FM476 315/433]\n"
    "PWM, Rolling Code\n"
    "\n"
    "V6 [FM476 315/433]\n"
    "Manchester, AES-128, CRC8\n"
    "\n"
    "V7 [FM476 315/433]\n"
    "Manchester, Rolling Code,\n"
    "CRC8\n"
    "\n"
    "Hyundai compatibles:\n"
    "Solaris 11-20, Accent\n"
    "11-20, Santa Fe 05-16,\n"
    "IX35 10-15, I10/I20/I30/\n"
    "I40, Sonata 09-17,\n"
    "Elantra 06-19, Tucson\n"
    "09-15, Veloster 11-17\n"
    "Kia compatibles:\n"
    "Rio 15-20, Cerato 03-19,\n"
    "Ceed 06-18, Soul 08-19,\n"
    "Optima 10-15, Picanto\n"
    "11-17, Stonic 17-20\n"
    "\n"
    "=== HONDA ===\n"
    "\n"
    "Static [Honda1 315/433]\n"
    "PWM, Static code, Checksum\n"
    "\n"
    "V1 [AM650 315/433]\n"
    "Manchester, Rolling Code,\n"
    "CRC4\n"
    "\n"
    "V2 [F4 315/433]\n"
    "PWM, Rolling Code\n"
    "\n"
    "Models:\n"
    "Accord 03-07, Stream 03-06\n"
    "\n"
    "=== FIAT ===\n"
    "\n"
    "V0 [AM650 315/433]\n"
    "Manchester, Rolling Code,\n"
    "static emulate only\n"
    "\n"
    "V1 [AM650 315/433]\n"
    "Manchester, HITAG2, XOR8\n"
    "Needs user key prompt\n"
    "\n"
    "V2 [AM650 315/433]\n"
    "Manchester, Rolling Code.\n"
    "Decode only\n"
    "\n"
    "=== OTHER CARS ===\n"
    "\n"
    "Chrysler V0 [AM650 315/433]\n"
    "PWM, Rolling Code\n"
    "\n"
    "Mazda V0 [AM650+F2 315/433]\n"
    "Manchester, Rolling Code,\n"
    "Checksum\n"
    "Models:\n"
    "Tribute 08-11, RX-8 etc.\n"
    "\n"
    "Mitsubishi V0 [FM476]\n"
    "PWM, Rolling Code\n"
    "Models:\n"
    "Pajero 06-20, L200 07-20,\n"
    "Galant/Grandis/Colt\n"
    "\n"
    "Porsche Touareg [AM650 315]\n"
    "PWM, Rolling Code\n"
    "\n"
    "Renault V0 [AM650 315/433]\n"
    "Manchester, Rolling/Replay\n"
    "\n"
    "Subaru [AM650 315/433]\n"
    "PPM, Rolling Code\n"
    "Models:\n"
    "Forester 07-17, Impreza\n"
    "00-16, Outback 00-14,\n"
    "Tribeca 05-14, Legacy 03-14\n"
    "\n"
    "=== ALARMS / AFTERMARKET ===\n"
    "\n"
    "StarLine [AM650 315/433]\n"
    "PWM, KeeLoq. Decode+Encode\n"
    "Models: A2/A4/A6/A8/A9,\n"
    "B6/B9, C6/C9, 24V\n"
    "\n"
    "Scher-Khan [FM 315/433]\n"
    "PWM, Magic Code\n"
    "Models: III, IV, 3-8,\n"
    "MAGICAR 7S/8S/11/12,\n"
    "Magicar M902/M903/M909\n"
    "\n"
    "=== ASTUCES TECHNIQUES ===\n"
    "\n"
    "CAPTURE:\n"
    "- Portee: 5-20m selon emetteur\n"
    "- Bloquer la porte/metaux\n"
    "  reduit la portee\n"
    "- Approcher le Flipper du\n"
    "  recepteur (pas de la clef)\n"
    "- Signal capture = utilisable\n"
    "  immediatement. Apres 1-2\n"
    "  appuis clef originale, le\n"
    "  signal expire (Renault).\n"
    "\n"
    "COMPTEUR ROLLING:\n"
    "- Hold OK 1 sec = catch-up\n"
    "+50 (utile si ouverture\n"
    "longtemps apres capture)\n"
    "- S'arrete si on eteint l'app.\n"
    "  Pas restaure au redemarrage\n"
    "- Kia Sorento/Carnival 2020+:\n"
    "  s'ouvrent avec 7 clics\n"
    "- StarLine/KeeLoq: compteur\n"
    "  incremente entre boutons\n"
    "- Si ouverture longtemps apres\n"
    "  capture: relancer +50 clics\n"
    "  (catch-up = 4+6 simultane)\n"
    "\n"
    "BRUTEFORCE / ENUMERATION:\n"
    "- Came: ~10 min, Nice: ~20 min\n"
    "- Nissan Qashqai/X-Trail: 6 min\n"
    "- VAZ/Lada: ~2.5 min\n"
    "- Renault smart cards: 3\n"
    "  groupes, 2 min par groupe.\n"
    "  Short press 3 = skip group\n"
    "- Si >2 min, signal perdu\n"
    "  (re-capturer).\n"
    "\n"
    "SPECIFICITES PAR MARQUE:\n"
    "- VAG: counter entre boutons,\n"
    "  s'arrete si app eteinte.\n"
    "  Re-capturer necessaire.\n"
    "- PSA/Citroen: signal utilise\n"
    "  avant que clef originale\n"
    "  ne soit repressee.\n"
    "- Renault Megane/Laguna:\n"
    "  smart card, 3 groupes de\n"
    "  recherche, skip possible.\n"
    "- Ford Power Start: bouton\n"
    "  demarrage sans clef.\n"
    "- Subaru: 433 MHz Europe only.\n"
    "\n"
    "JAMMING / BROUILLAGE:\n"
    "- Actif = bloque 433 MHz\n"
    "- Utile pour empecher la\n"
    "  voiture de recevoir le\n"
    "  signal original pendant\n"
    "  que tu captures.\n"
    "- Pause jamming: bouton 1\n"
    "- Switch freq: bouton 4\n"
    "\n"
    "=== LEGEND ===\n"
    "\n"
    "AM650 = AM OOK 650 kHz\n"
    "F4 = 4FSK (FM)\n"
    "FM476 = 4FSK 476 kHz\n"
    "Honda1 = Honda protocol\n"
    "F3/F2 = Other FM variants\n"
    "\n"
    "=== CREDITS ===\n"
    "\n"
    "ProtoPirate by The Pirates'\n"
    "Plunder. Fork by Carlitack.\n"
    "Protocabrax v1.0\n"
    "Compiled with FlipperFAP\n"
    "flipper0.com\n";

void protopirate_scene_protocol_help_on_enter(void* context) {
    furi_check(context);
    ProtoPirateApp* app = context;

    if(!protopirate_ensure_widget(app)) {
        FURI_LOG_E(TAG, "Failed to allocate widget");
        notification_message(app->notifications, &sequence_error);
        scene_manager_previous_scene(app->scene_manager);
        return;
    }

    widget_reset(app->widget);
    widget_add_text_scroll_element(app->widget, 0, 0, 128, 64, help_text);
    view_dispatcher_switch_to_view(app->view_dispatcher, ProtoPirateViewWidget);
}

bool protopirate_scene_protocol_help_on_event(void* context, SceneManagerEvent event) {
    UNUSED(context);
    UNUSED(event);
    return false;
}

void protopirate_scene_protocol_help_on_exit(void* context) {
    furi_check(context);
    ProtoPirateApp* app = context;
    widget_reset(app->widget);
}
